package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class StudentDAO {

    /**
     * Retrieves a list of available exams for a specific student.
     * It checks their track, their courses, and excludes exams they already took.
     */
    public List<Object[]> getAvailableExams(int studentId) {
        List<Object[]> availableExams = new ArrayList<>();

        // This query joins Student_Track -> Track_Course -> Course -> Exam
        // and uses a subquery to filter out exams already present in StudentExam
        String query =
                "SELECT E.ExamID, E.ExamName, C.CourseName, E.DurationMinutes, E.TotalQuestions " +
                        "FROM Exam E " +
                        "INNER JOIN Course C ON E.CourseID = C.CourseID " +
                        "INNER JOIN Track_Course TC ON C.CourseID = TC.CourseID " +
                        "INNER JOIN Student_Track ST ON TC.TrackID = ST.TrackID " +
                        "WHERE ST.StudentID = ? " +
                        "AND E.ExamID NOT IN (SELECT ExamID FROM StudentExam WHERE StudentID = ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {

            // Pass the student ID to both the WHERE clause and the subquery
            pstmt.setInt(1, studentId);
            pstmt.setInt(2, studentId);

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("ExamID");
                row[1] = rs.getString("ExamName");
                row[2] = rs.getString("CourseName");
                row[3] = rs.getInt("DurationMinutes");
                row[4] = rs.getInt("TotalQuestions");
                availableExams.add(row);
            }
        } catch (SQLException e) {
            System.err.println("Error fetching available exams: " + e.getMessage());
        }

        return availableExams;
    }
    // You can paste this right inside your StudentDAO class, at the bottom
    public static class ExamQuestionDTO {
        public int questionId;
        public String questionText;
        public String questionType;
        // LinkedHashMap keeps the options in the exact order they come from the database
        public java.util.LinkedHashMap<Integer, String> options = new java.util.LinkedHashMap<>();
    }
    /**
     * Fetches all questions and their corresponding options for a specific exam.
     */
    public List<ExamQuestionDTO> getExamQuestions(int examId) {
        List<ExamQuestionDTO> questionList = new ArrayList<>();

        // This query fetches the questions ordered by the randomization (OrderNo)
        // generated by your GenerateExam stored procedure.
        String query =
                "SELECT EQ.QuestionID, Q.QuestionText, Q.QuestionType, O.OptionID, O.OptionText " +
                        "FROM ExamQuestion EQ " +
                        "INNER JOIN Question Q ON EQ.QuestionID = Q.QuestionID " +
                        "INNER JOIN [Option] O ON Q.QuestionID = O.QuestionID " +
                        "WHERE EQ.ExamID = ? " +
                        "ORDER BY EQ.OrderNo, O.OptionID";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setInt(1, examId);
            ResultSet rs = pstmt.executeQuery();

            ExamQuestionDTO currentQuestion = null;

            while (rs.next()) {
                int qId = rs.getInt("QuestionID");

                // If we are looking at a new QuestionID, create a new DTO
                if (currentQuestion == null || currentQuestion.questionId != qId) {
                    currentQuestion = new ExamQuestionDTO();
                    currentQuestion.questionId = qId;
                    currentQuestion.questionText = rs.getString("QuestionText");
                    currentQuestion.questionType = rs.getString("QuestionType");
                    questionList.add(currentQuestion);
                }

                // Add the option to the current question's map
                currentQuestion.options.put(rs.getInt("OptionID"), rs.getString("OptionText"));
            }

        } catch (SQLException e) {
            System.err.println("Error fetching exam questions: " + e.getMessage());
        }

        return questionList;
    }
    /**
     * Converts the student's answers to XML and calls the SubmitExamAnswers stored procedure.
     */
    /**
     * Converts answers to XML, calls SubmitExamAnswers, and triggers CorrectExam for grading.
     */
    public boolean submitExam(int studentId, int examId, Map<Integer, Integer> answers) {
        // 1. Build the XML String using XML Elements (Matches teammate's XQuery)
        StringBuilder xmlBuilder = new StringBuilder("<Answers>");
        for (Map.Entry<Integer, Integer> entry : answers.entrySet()) {
            xmlBuilder.append("<Answer>")
                    .append("<QuestionID>").append(entry.getKey()).append("</QuestionID>")
                    .append("<ChosenOptionID>").append(entry.getValue()).append("</ChosenOptionID>")
                    .append("</Answer>");
        }
        xmlBuilder.append("</Answers>");
        String xmlAnswers = xmlBuilder.toString();

        // 2. Generate Timestamps for the SQL DATETIME parameters
        // We'll record the end time as right now, and start time as 1 hour ago
        java.sql.Timestamp endTime = new java.sql.Timestamp(System.currentTimeMillis());
        java.sql.Timestamp startTime = new java.sql.Timestamp(System.currentTimeMillis() - (60 * 60 * 1000));

        // 3. Call the teammate's SubmitExamAnswers procedure
        String callSubmit = "{call SubmitExamAnswers(?, ?, ?, ?, ?)}";

        try (java.sql.Connection conn = DatabaseConnection.getConnection();
             java.sql.CallableStatement cstmt = conn.prepareCall(callSubmit)) {

            // Note the exact order: StudentID, ExamID, Start, End, XML
            cstmt.setInt(1, studentId);
            cstmt.setInt(2, examId);
            cstmt.setTimestamp(3, startTime);
            cstmt.setTimestamp(4, endTime);
            cstmt.setString(5, xmlAnswers);

            cstmt.execute(); // Exam is now submitted!

            // 4. GRADING: We must find the new StudentExamID and call CorrectExam
            String getExamIdQuery = "SELECT TOP 1 StudentExamID FROM StudentExam WHERE StudentID = ? AND ExamID = ? ORDER BY StudentExamID DESC";
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement(getExamIdQuery)) {
                pstmt.setInt(1, studentId);
                pstmt.setInt(2, examId);
                java.sql.ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    int studentExamId = rs.getInt("StudentExamID");

                    // Call the teammate's CorrectExam procedure
                    try (java.sql.CallableStatement correctStmt = conn.prepareCall("{call CorrectExam(?)}")) {
                        correctStmt.setInt(1, studentExamId);
                        correctStmt.execute();
                    }
                }
            }

            return true;

        } catch (java.sql.SQLException e) {
            System.err.println("Error submitting exam: " + e.getMessage());
            return false;
        }
    }
}

