# SQL Server Connection Properties (Change to your own)
db.url=jdbc:sqlserver://localhost:50264;databaseName=ITI_ExamSystem;encrypt=true;trustServerCertificate=true;
db.user=iti_admin
db.password=Admin@ITI2024

